### ISSUE TITLE
Time for a replaced dependency is NIL, causing a panic error

### ISSUE THREAD

**Issue by mdelapenya** [elastic/go-licence-detector#11]
Hi! I have this `go.mod` file:
```go
require (
	github.com/Jeffail/gabs/v2 v2.5.1
	github.com/cenkalti/backoff/v4 v4.0.2
	github.com/cucumber/godog v0.9.0
	github.com/elastic/e2e-testing/cli v0.0.0-20200717181709-15d2db53ded7
	github.com/elastic/go-elasticsearch/v8 v8.0.0-20190731061900-ea052088db25
	github.com/sirupsen/logrus v1.4.2
)

replace github.com/elastic/e2e-testing/cli v0.0.0-20200717181709-15d2db53ded7 => ../cli
```
but when I run the tool with a Make target I have in the repository:
```make
 make notice
Generating NOTICE
go mod tidy
go mod download
go list -m -json all | go run go.elastic.co/go-licence-detector \
                -includeIndirect \
                -rules ../notice/rules.json \
                -overrides ../notice/overrides.json \
                -noticeTemplate ../notice/NOTICE.txt.tmpl \
                -noticeOut NOTICE.txt \
                -depsOut ""
```

I got this stacktrace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1373dd1]

goroutine 1 [running]:
go.elastic.co/go-licence-detector/detector.mkDepInfo(0xc002a81950, 0xc0038121e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/mdelapenya/sourcecode/pkg/mod/go.elastic.co/go-licence-detector@v0.4.0/detector/detector.go:213 +0x1c1
go.elastic.co/go-licence-detector/detector.doDetectLicences(0xc00cd71360, 0xc00000e4c0, 0xc00d190250, 0xc003be0200, 0x6, 0x8, 0xc0038121e0, 0x1fdefa0, 0xc000070060, 0xc0038125a0, ...)
        /Users/mdelapenya/sourcecode/pkg/mod/go.elastic.co/go-licence-detector@v0.4.0/detector/detector.go:152 +0xaf
go.elastic.co/go-licence-detector/detector.detectLicences(0xc00000e4c0, 0xc00d190250, 0xc0038125a0, 0xc0038121e0, 0x0, 0x0, 0x6abe7d8)
        /Users/mdelapenya/sourcecode/pkg/mod/go.elastic.co/go-licence-detector@v0.4.0/detector/detector.go:134 +0x97
go.elastic.co/go-licence-detector/detector.Detect(0x6abe7d8, 0xc0000717a0, 0xc00000e4c0, 0xc00d190250, 0xc0038121e0, 0x1, 0x18, 0xc000cce2fd, 0xc000171ed8)
        /Users/mdelapenya/sourcecode/pkg/mod/go.elastic.co/go-licence-detector@v0.4.0/detector/detector.go:102 +0xa0
main.main()
        /Users/mdelapenya/sourcecode/pkg/mod/go.elastic.co/go-licence-detector@v0.4.0/main.go:75 +0x327
exit status 2
make: *** [notice] Error 1
```

A sample PR and workspace can be found here: https://github.com/elastic/e2e-testing/pull/180

**Comment by charith-elastic** [comment]
Supporting local replacements is a bit tricky because of the timestamp issue you have just run into and also because their names are reported by Go as relative paths. In this particular case, your replaced dependency will be reported as `../cli` instead of `github.com/elastic/e2e-testing/cli`. The workaround is easy but I was hesitant to add it because it felt like there would be some non-obvious edge cases. 

Since you seem to have a genuine need now, I will try to add that workaround at least temporarily.

**Comment by charith-elastic** [comment]
After looking at this a bit more, I don't think there's a very good way of supporting replace directives for local paths. The complications are as follows:

- The replace path can be anywhere in the file system. So it's not guaranteed to be part of the checked out project nor be at the same version (I could have version 1.2 checked out at the path but on your machine that path could be pointing to version 2.4). This means that the results we produce are environment-specific and hard to reproduce reliably.
- The reported location of the replacement module is not rooted at the Go module cache. As the licence-detector can be run from anywhere in the file system, this makes it quite complicated to strip out the environment-specific paths out of that path. Furthermore, it's a potential security risk as someone could craft a replace directive that makes the licence-detector spit out a system file inadvertently.

So I am inclined to not fix this issue in the licence-detector code. In your particular case, as the modules seem to depend on each other, is  there a particular reason why the project doesn't have a single go module at the root of `e2e-testing`?

**Comment by mdelapenya** [comment]
Well, the idea is to have both projects in separation: the provisioner/cli side to be consumed as a separated CLI to provision docker container for observability; and the different `tests` will consume the first project as a library.

Would it be possible to create an overrides rule for this use case?

**Comment by charith-elastic** [comment]
> Well, the idea is to have both projects in separation

Since both modules are in the same GitHub repo, I don't think you gain much as Go needs to download the whole repo anyway [needs verification]

> Would it be possible to create an overrides rule for this use case?

Since the version and timestamp are not available for local replacements, that means we need to ask the user to provide pretty much all the details about the dependency in the override rule. The danger there is that it could quickly go out of sync with the actual state of things.

**Comment by charith-elastic** [comment]
You may be able to use the existing override rules to work around this by using `../cli` as the module name. I am currently in the middle of a release. I'll test it out later tomorrow when I have time.
